### ISSUE TITLE
Faceting plots fails when the selected variable has a space in its name

### ISSUE THREAD

**Issue by mneinast** [MRMacArthur/TracebaseView#2]
# description

In the plot generation sidebar, faceting by variables which have spaces in the name fails.  For example, faceting by `Tissue` works, but faceting by `Measured Compound(s)` fails.

# Steps to reproduce:
1. load PeakGroups data
2. check box to facet by 1 variable
3. select `Tissues` -> plot should work properly
4. select `Measured Compound(s)` -> plot should fail.

# Suggested changes
option 1:  rename variables during upload to eliminate spaces in names
option 2:  clever parsing tricks within the facet() function?

_I might go for option 1 since this would make working with these variable names easier throughout R...perhaps specific rules could be used (ie spaces always replaced with period)_

**Comment by MRMacArthur** [comment]
Decided to go with option 2 because still hoping to keep unaltered variable names for plotting aesthetics. To fix this, the `input$facet` args were wrapped in a `paste` call to insert ` characters.
