### ISSUE TITLE
Time Collected is imported as string, but should be double

### ISSUE THREAD

**Issue by mneinast** [MRMacArthur/TracebaseView#4]
# description
The recent TraceBase updates now include `Time Collected (m)` as a field in all downloaded data.  It appears R is importing this as a string, because it prefers to order these values alphabetically instead of numerically.

# Steps to reproduce

1. load new PeakGroups data (as of 230210) that includes multiple timepoints (ie `CB_TCA Flux in Healthy Tissues`)
2. select anything in Data Input page.
3. In X Axis, select `Time Collected (m)`.
4. Select anything in Y axis.
5. Plotted data should have time values in x axis in alphabetic order instead of numeric.

# Suggested changes

Manually convert `Time Collected (m)` to double.  This field will sometimes include digits beyond decimal (ie 1.5 minutes).

**Comment by MRMacArthur** [comment]
Fixed. Variables are split into numeric vs categorical lists using the hardcoded vectors `summaryColNames` and `numericColNames` in the `server.R` script. These variables are then coerced to the appropriate datatype in the `getData()` function based on these vectors. I switched `Time Collected (m)` to the vector of numeric variables.
